windowrulev1 = opacity 0.8 0.7, tag:terminal
windowrulev1 = opacity 0.9 0.7, tag:browser
windowrulev1 = workspace 1, tag:email
windowrulev1 = workspace 2, tag:browser
windowrulev1 = workspace 4 silent, tag:screenshare
windowrulev1 = workspace 5, tag:gamestore
windowrulev1 = workspace 6 silent, class:^(virt-manager)$
windowrulev1 = workspace 6 silent, class:^(.virt-manager-wrapped)$
windowrulev1 = workspace 7, tag:im
windowrulev1 = workspace 8, tag:games
windowrulev1 = workspace 9 silent, tag:multimedia