windowrulev2 = opacity 0.8 0.7, tag:terminal
windowrulev2 = opacity 0.9 0.7, tag:browser
windowrulev2 = workspace 1, tag:email
windowrulev2 = workspace 2, tag:browser
windowrulev2 = workspace 4 silent, tag:screenshare
windowrulev2 = workspace 5, tag:gamestore
windowrulev2 = workspace 6 silent, class:^(virt-manager)$
windowrulev2 = workspace 6 silent, class:^(.virt-manager-wrapped)$
windowrulev2 = workspace 7, tag:im
windowrulev2 = workspace 8, tag:games
windowrulev2 = workspace 9 silent, tag:multimedia